=== Pante/XMC-Framework/src/main/resources/dtd/commands.dtd
<!ELEMENT commands (command+)>

<!ELEMENT command (meta, permission, (commands|configuration))>
<!ATTLIST command
  name CDATA #REQUIRED
>

<!ELEMENT meta EMPTY>
<!ATTLIST meta
  aliases CDATA ""
  description CDATA "No description for command"
  usage CDATA "No usage for command"
>

<!ELEMENT permission EMPTY>
<!ATTLIST permission
  permission CDATA ""
  message CDATA "You do not have permission to use this command."
  allow-console (true|false) "false"
>

<!ELEMENT configuration (cooldown*, worlds*)>

<!ELEMENT cooldown EMPTY>
<!ATTLIST cooldown
  time CDATA "0"
>

<!ELEMENT worlds EMPTY>
<!ATTLIST worlds
  type (whitelist|blacklist) #REQUIRED
  list CDATA #REQUIRED
>

=== Pante/XMC-Framework/src/main/resources/example/commands.xml
<?xml version = "1.0" encoding = "UTF-8"?>
 
<!-- 
 Example commands.xml
 All element attriutes will default to a safe value if unpresent unless otherwise stated.
-->


<!-- Mandatory document type definition (DTD) needed for XMC to parse the document -->
<!DOCTYPE commands SYSTEM "commands.dtd">

<commands>
  
  <!-- Attribute: name is mandatory for obvious reasons -->
  <command name = "command">
    
    <meta aliases = "cmd, comm" description = "command description" usage = "example usage"/>
    <permission permission = "example.permission" message = "You do not have permission to use this command" allow-console = "true"/>
    
    
    <!-- 
    Commands can only either have child commands as defined by the element: <commands> 
    or be configurable as defined by the element: <configuration>.
    If both of the above elements are present, XMC will only parse the element which 
    comes first and ignore the subsequent one(s). This is to ensure that configuration 
    is delegated to the child commands to prevent hierarchical conflicts.
    -->
    <commands>
      
      <command name = "subcommand">
    
        <meta aliases = "subcmd, subcomm" description = "command description" usage = "example usage"/>
        <permission permission = "example.permission" message = "You do not have permission to use this command" allow-console = "true"/>
      
      
        <!--
        A default value must be specified for the command to be configurable under the 
        commands-configuration.xml document. XMC will ignore said configuuration option if 
        no default value is present.
        -->
        <configuration>
      
          <!-- The time unit for attribute: time is in milliseconds -->
          <cooldown time = "10"/>
        
          <!-- Valid values for attribute: type are "whitelist" and "blacklist" -->
          <worlds type = "whitelist" list = "world1, world2"/>
        
        </configuration>
        
      </command>
    
    </commands>
    
  </command>
  
</commands>
