=== Pante/XMC-Framework/src/main/resources/items.xsd
<?xml version="1.0"?>
<!--
Copyright (C) 2017 PanteLegacy @ karusmc.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:complexType name = "enchantmentsType">
        <xs:sequence>
            <xs:element name = "enchantment" minOccurs = "1" maxOccurs = "unbounded">
                <xs:complexType>
                    <xs:attribute name = "type" type = "xs:string" use = "required"/>
                    <xs:attribute name = "level" type = "xs:positiveInteger" default = "1"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    
    <xs:element name = "item-meta" type = "itemType"/>
        
    <xs:complexType name = "itemType">
            <xs:sequence>
                
                <xs:element name = "enchantments" type = "enchantmentsType" minOccurs = "0" maxOccurs = "1"/>
                
                <xs:element name = "description" minOccurs = "0" maxOccurs = "1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "line" type = "xs:string" minOccurs = "1" maxOccurs = "unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name = "flags" minOccurs = "0" maxOccurs = "1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name = "flag" type = "xs:string" minOccurs = "1" maxOccurs = "unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
            </xs:sequence>
            <xs:attribute name = "display-name" type = "xs:string"/>
    </xs:complexType>
    
    
    <xs:element name = "banner-meta" type = "bannerType"/>
    
    <xs:complexType name = "bannerType">
        <xs:complexContent>
            <xs:extension base = "itemType">
                <xs:sequence>
                    
                    <xs:element name = "patterns" minOccurs = "0" maxOccurs = "1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name = "pattern">
                                    <xs:complexType>
                                        <xs:attribute name = "type" type = "xs:string" use = "required"/>
                                        <xs:attribute name = "color" type = "xs:string" use = "required"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    
    <xs:element name = "book-meta" type = "bookType"/>
    
    <xs:complexType name = "bookType">
        <xs:complexContent>
            <xs:extension base = "itemType">
                
                <xs:sequence>
                    <xs:element name = "pages" minOccurs = "0" maxOccurs = "1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name = "page" type = "xs:string" minOccurs = "1" maxOccurs = "unbounded"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
                <xs:attribute name = "title" type = "xs:string" use = "required"/>
                <xs:attribute name = "author" type = "xs:string" use = "required"/>
                
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    
    <xs:element name = "leather-armour-meta" type = "leatherArmorType"/>
    
    <xs:complexType name = "leatherArmorType">
        <xs:complexContent>
            <xs:extension base = "itemType">
                <xs:attribute name = "r" type = "xs:nonNegativeInteger" default = "0"/>
                <xs:attribute name = "g" type = "xs:nonNegativeInteger" default = "0"/>
                <xs:attribute name = "b" type = "xs:nonNegativeInteger" default = "0"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    
    <xs:element name = "potion-meta" type = "potionType"/>
    
    <xs:complexType name = "potionType">
        <xs:complexContent>
            <xs:extension base = "itemType">
                <xs:sequence>
                    
                    <xs:element name = "effects" minOccurs = "0" maxOccurs = "1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name = "effect">
                                    <xs:complexType>
                                        <xs:attribute name = "type" type = "xs:string" use = "required"/>
                                        <xs:attribute name = "duration" type = "xs:nonNegativeInteger" use = "required"/>
                                        <xs:attribute name = "level" type = "xs:positiveInteger" use = "required"/>
                                        <xs:attribute name = "ambient" type = "xs:boolean" default = "false"/>
                                        <xs:attribute name = "particles" type = "xs:boolean" default = "true"/>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    
                </xs:sequence>
                <xs:attribute name = "color" type = "xs:string" default = "ORANGE"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    
    <xs:element name = "storage-meta" type = "storageType"/>
    
    <xs:complexType name = "storageType">
        <xs:complexContent>
            <xs:extension base = "itemType">
                <xs:sequence>
                    
                    <xs:element name = "stored" type = "enchantmentsType" minOccurs = "0" maxOccurs = "1"/>
                    
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    
    
    
    
    <xs:element name = "items">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "item" minOccurs = "1" maxOccurs = "unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            
                            <xs:element name = "value" minOccurs = "0" maxOccurs = "1">
                                <xs:complexType>
                                    <xs:attribute name = "buy" type = "xs:float" default = "0"/>
                                    <xs:attribute name = "sell" type = "xs:float" default = "0"/>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:choice>
                                <xs:element name = "banner-meta" type = "bannerType"/>
                                <xs:element name = "book-meta" type = "bookType"/>
                                <xs:element name = "item-meta" type = "itemType"/>
                                <xs:element name = "leather-armor-meta" type = "leatherArmorType"/>
                                <xs:element name = "potion-meta" type = "potionType"/>
                                <xs:element name = "storage-meta" type = "storageType"/>
                            </xs:choice>
                            
                        </xs:sequence>
                        
                        <xs:attribute name = "name" type = "xs:string" use = "required"/>
                        <xs:attribute name = "type" type = "xs:string" use = "required"/>
                        <xs:attribute name = "amount" type = "xs:positiveInteger" default = "1"/>
                        <xs:attribute name = "data" type = "xs:short" default = "0"/>
                        
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Pante/XMC-Framework/src/test/resources/items.xml
<?xml version="1.0" encoding="UTF-8"?>


<items xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation = "items.xsd"
>
    
    <item name = "banner" type = "BANNER" amount = "16" data = "0">
        <value buy = "10.00" sell = "50.00"/>
        <banner-meta display-name = "&amp;cItem">
            <enchantments>
                <enchantment type = "PROTECTION_ENVIRONMENTAL" level = "1"/>
            </enchantments>
            
            <description>
                <line>Line one</line>
                <line>Line Two</line>
            </description>
            
            <flags>
                <flag>HIDE_DESTROYS</flag>
            </flags>
            
            <patterns>
                <pattern type = "BORDER" color = "CYAN"/>
            </patterns>
        </banner-meta>
    </item>
    
    <item name = "written book" type = "WRITTEN_BOOK" amount = "16" data = "0">
        <value buy = "10.00" sell = "50.00"/>
        <book-meta display-name = "&amp;cItem" author = "Aldous Huxley" title = "&amp;cBrave New World">      
            <enchantments>
                <enchantment type = "PROTECTION_ENVIRONMENTAL" level = "3"/>
            </enchantments>
    
            <description>
                <line>Line 1</line>
                <line>Line 2</line>
            </description>
    
            <flags>
                <flag>HIDE_DESTROYS</flag>
            </flags>
    
            <pages>
                <page>&amp;cSQUAT grey building of only thirty-four stories.</page>
            </pages>
    
        </book-meta>
    </item>
    
    <item name = "raw beef" type = "RAW_BEEF" amount = "16" data = "0">
        <value buy = "10.00" sell = "50.00"/>
        <item-meta display-name = "&amp;cItem">
            <enchantments>
                <enchantment type = "PROTECTION_ENVIRONMENTAL" level = "3"/>
            </enchantments>
    
            <description>
                <line>Line 1</line>
                <line>Line 2</line>
            </description>
    
            <flags>
                <flag>HIDE_DESTROYS</flag>
            </flags>
        </item-meta>
    </item>
    
    <item name = "leather boots" type = "LEATHER_BOOTS" amount = "16" data = "0">
        <value buy = "10.00" sell = "50.00"/>
        <leather-armor-meta display-name = "&amp;cItem" r = "1" g = "2" b = "3">
      
            <enchantments>
                <enchantment type = "PROTECTION_ENVIRONMENTAL" level = "3"/>
            </enchantments>
    
            <description>
                <line>Line 1</line>
                <line>Line 2</line>
            </description>
    
            <flags>
                <flag>HIDE_DESTROYS</flag>
            </flags>
    
        </leather-armor-meta>
    </item>
    
    <item name = "potion" type = "POTION" amount = "16" data = "0">
        <value buy = "10.00" sell = "50.00"/>
        <potion-meta display-name = "&amp;cItem" color = "SILVER">
      
            <enchantments>
                <enchantment type = "PROTECTION_ENVIRONMENTAL" level = "3"/>
            </enchantments>
    
            <description>
                <line>Line 1</line>
                <line>Line 2</line>
            </description>
    
            <flags>
                <flag>HIDE_DESTROYS</flag>
            </flags>
    
            <effects>
                <effect type = "JUMP" duration = "10" level = "3" ambient = "true" particles = "true"/>
            </effects>
    
        </potion-meta>
    </item>
    
    <item name = "enchanted book" type = "ENCHANTED_BOOK" amount = "16" data = "0">
        <value buy = "10.00" sell = "50.00"/>
        <storage-meta display-name = "&amp;cItem">
      
            <enchantments>
                <enchantment type = "PROTECTION_ENVIRONMENTAL" level = "3"/>
            </enchantments>
    
            <description>
                <line>Line 1</line>
                <line>Line 2</line>
            </description>
    
            <flags>
                <flag>HIDE_DESTROYS</flag>
            </flags>
    
            <stored>
                <enchantment type = "PROTECTION_ENVIRONMENTAL" level = "3"/>
            </stored>
    
        </storage-meta>
    </item>
    
</items>
