=== Pante/XMC-Framework/src/test/resources/commands.xsd
<?xml version="1.0"?>
<!--
Copyright (C) 2017 PanteLegacy @ karusmc.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    
    <xs:complexType name = "commandsType">
        <xs:sequence>
            <xs:element name = "command" type = "commandType" minOccurs = "1" maxOccurs = "unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name = "commands" type = "commandsType"/>
    
    <xs:complexType name = "commandType">
        <xs:sequence>
            
            <xs:element name = "meta">
                <xs:complexType>
                    <xs:attribute name = "aliases" type = "xs:string" default = ""/>
                    <xs:attribute name = "description" type = "xs:string" default = ""/>
                    <xs:attribute name = "usage" type = "xs:string" default = ""/>
                </xs:complexType>
            </xs:element>
            
            <xs:element name = "permission">
                <xs:complexType>
                    <xs:attribute name = "permission" type = "xs:string" use = "required"/>
                    <xs:attribute name = "message" type = "xs:string" default = ""/>
                </xs:complexType>
            </xs:element>
            
            <xs:element name = "commands" type = "commandsType" minOccurs = "0" maxOccurs = "1"/>
            
        </xs:sequence>
        <xs:attribute name = "name" type = "xs:string" use = "required"/>
    </xs:complexType>
    
</xs:schema>

=== Pante/XMC-Framework/Commands/src/main/resources/commands.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<commands xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation = "commands.xsd"
>
    
  <command name = "command">
    <meta aliases = "cmd, comm" description = "command description" usage = "example usage"/>
    <permission permission = "example.permission" message = "You do not have permission to use this command"/>
    <commands>
        
      <command name = "subcommand">
        <meta aliases = "subcmd, subcomm" description = "command description" usage = "example usage"/>
        <permission permission = "example.permission" message = "You do not have permission to use this command"/>
      </command>
      
    </commands>
  </command>
  
</commands>

=== Pante/XMC-Framework/src/main/resources/commands.xml
<?xml version = "1.0" encoding = "UTF-8"?>

<commands xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation = "commands.xsd"
>
    
  <command name = "command">
    <meta aliases = "cmd, comm" description = "command description" usage = "command usage"/>
    <permission permission = "command.permission" message = "You do not have permission to use this command"/>
    
    <commands>
        
      <command name = "subcommand">
        <meta aliases = "subcmd, subcomm" description = "subcommand description" usage = "subcommand usage"/>
        <permission permission = "subcommand.permission" message = "You do not have permission to use this subcommand"/>
      </command>
      
    </commands>
  </command>
  
</commands>
